version: '3.7'

services:
  back_app:
    build: ./backend
    container_name: api
    ports:
      - 3000:3000
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      - backend
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
networks:
  backend:
    driver: bridge

volumes:
    mongodb:
    mongodb_config: